name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Install deps
        run: poetry install

      - name: Run linters
        run: poetry run black --check src tests

      - name: Run type checks
        run: poetry run mypy src

      - name: Run tests
        run: poetry run pytest -v

